services:
  postgres:
    image: postgres:18
    container_name: reticket-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reticket
      POSTGRES_USER: reticket
      POSTGRES_PASSWORD: reticket
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: