services:
  postgres:
    image: postgres:18
    container_name: reticket-postgres

    environment:
      POSTGRES_DB: reticket
      POSTGRES_USER: reticket
      POSTGRES_PASSWORD: reticket

    ports:
      - "5432:5432"

    volumes:
      - reticket-postgres-data:/var/lib/postgresql/data

volumes:
  reticket-postgres-data: